development:
  adapter: postgresql
  database: db_dev
  pool: 5
  timeout: 5000
  username: postgres
  password: hola123jaja

test:
  adapter: postgresql
  database: db_test
  pool: 5
  timeout: 5000
  username: postgres
  password: hola123jaja

production:
  adapter: postgresql
  database: db_prod
  pool: 5
  timeout: 5000
  username: postgres
  password: hola123jaja
